apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity
  namespace: towerdefence

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: towerdefence
  name: service-reader

rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-access
  namespace: towerdefence

subjects:
  - kind: ServiceAccount
    name: velocity
  - kind: ServiceAccount
    name: custom-agones-sdk

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-reader
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-agones-sdk-access-velocity
  namespace: towerdefence

subjects:
  - kind: ServiceAccount
    name: velocity

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk

---