apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-manager
  namespace: towerdefence
  labels:
    app: friend-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend-manager

  template:
    metadata:
      labels:
        app: friend-manager
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/towerdefence-cc/friend-manager-service:0759590ac5729fdf569edcaae1bdbb44593bb570
          ports:
            - containerPort: 9090

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "production"
            - name: "SPRING_DATA_MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard

      serviceAccountName: friend-manager
      automountServiceAccountToken: true
---

apiVersion: v1
kind: Service

metadata:
  namespace: towerdefence
  name: friend-manager

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: friend-manager

