# todo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-player
  namespace: towerdefence
  labels:
    app: mc-player

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-player

  template:
    metadata:
      labels:
        app: mc-player
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/towerdefence-cc/mc-player-service:c7d210939ebf9d3a0d83a895e0d6f4dc2e373147
          ports:
            - containerPort: 9090

          env:
            - name: "SPRING_DATA_MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
---

apiVersion: v1
kind: Service

metadata:
  namespace: towerdefence
  name: mc-player

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: mc-player
---

apiVersion: v1
kind: Service

metadata:
  namespace: towerdefence
  name: mc-player-security

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: mc-player

