apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  namespace: towerdefence
  labels:
    app: permission

spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission

  template:
    metadata:
      labels:
        app: permission
    spec:
      containers:
        - name: permission
          image: ghcr.io/towerdefence-cc/permission-service:32942b282af04229fbaedf7c2ecae72532242639
          ports:
            - containerPort: 9090

          env:
            - name: "SPRING_DATA_MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
---

apiVersion: v1
kind: Service

metadata:
  namespace: towerdefence
  name: permission

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: permission

