apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-discovery
  namespace: towerdefence
  labels:
    app: server-discovery

spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-discovery

  template:
    metadata:
      labels:
        app: server-discovery
    spec:
      containers:
        - name: server-discovery
          image: ghcr.io/towerdefence-cc/towerdefence-cc/server-discovery:29884ec761833580c263ddd7476ae31ab0750dff
          ports:
            - containerPort: 9090

          volumeMounts:
            - mountPath: "/secrets/keys"
              name: "keys"
              readOnly: true

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "production"
            - name: "AGONES_ALLOCATOR_ADDRESS"
              valueFrom:
                configMapKeyRef:
                  name: agones-allocator
                  key: address
                  optional: false
            - name: "AGONES_ALLOCATOR_PORT"
              valueFrom:
                configMapKeyRef:
                  name: agones-allocator
                  key: port
                  optional: false
      volumes:
        - name: "keys"
          projected:
            sources:
              - secret:
                  name: "allocator-client.custom"
                  optional: false
              - secret:
                  name: "allocator-client-ca.custom"
                  optional: false


---

apiVersion: v1
kind: Service

metadata:
  namespace: towerdefence
  name: server-discovery

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: server-discovery