# This is just an example that this secret should exist. Do not use this definition, create your own secret.
#apiVersion: v1
#kind: Secret
#metadata:
#  name: velocity-forwarding-token
#  namespace: towerdefence
#
#type: Opaque
#data:
#  forwarding.secret: "nXCx8fPh2b4M"

---

apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: "velocity"
  namespace: towerdefence

spec:
  replicas: 1
  scheduling: Packed

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      generateName: "velocity"
      namespace: towerdefence

    spec:
      ports:
        - name: default
          portPolicy: Static
          hostPort: 25565
          containerPort: 25565
          protocol: TCP
        - name: remove-management-tcp
          portPolicy: Static
          hostPort: 9091
          containerPort: 9091
          protocol: TCP
        - name: remove-management-udp
          portPolicy: Static
          hostPort: 9091
          containerPort: 9091
          protocol: UDP

      health:
        initialDelaySeconds: 10
        periodSeconds: 6
        failureThreshold: 2

      template:
        spec:
          containers:
            - name: velocity
              image: ghcr.io/towerdefence-cc/velocity:1.0.116
              imagePullPolicy: IfNotPresent

              ports:
                - containerPort: 9090
                  name: grpc
                  protocol: TCP

              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh", "-c", "echo $VELOCITY_FORWARDING_SECRET > /velocity/forwarding.secret" ]

              env:
                - name: VELOCITY_FORWARDING_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false

              resources:
                limits:
                  memory: "12Gi"
                  cpu: "12"
                requests:
                  memory: "11Gi"
                  cpu: "500m"

          serviceAccountName: velocity
          automountServiceAccountToken: true
