apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: towerdefence

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-access
  namespace: towerdefence

subjects:
  - kind: ServiceAccount
    name: friend-manager
  - kind: ServiceAccount
    name: private-message

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader