apiVersion: v1
kind: ServiceAccount
metadata:
  name: friend-manager
  namespace: towerdefence

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-message
  namespace: towerdefence

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity
  namespace: towerdefence